services:
  postgres:
    image: postgres:15-alpine
    container_name: bankcards_db
    restart: always
    environment:
      POSTGRES_DB: bankcardsdb
      POSTGRES_USER: bankuser
      POSTGRES_PASSWORD: bankpass123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bankuser -d bankcardsdb"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  default:
    driver: bridge